### ISSUE TITLE
Personal stats application

### ISSUE THREAD

**Issue by ozziest** [aftershift/aftershift.github.io#2]
We can create an application which can collect personal stats from different application such as GitHub, GitLab, Twitter or Spotify.

**Comment by UmutCakar** [comment]
Very nice I like it.

**Comment by UmutCakar** [comment]
I'd like to analyze the stock market.

**Comment by gormelof** [comment]
Hi @ozziest 

If we think in general.

- User Registration
- The user connect accounts like Github, Gitlab, Spotify etc.
- Personal data is collect for the user.
- Meaningful data is displayed to the user. (You have listened to 65% rock music in the last 1 month, The first five repository you've starred in the last week etc.)

Are you thinking of an application like this?

**Comment by gormelof** [comment]
> I would like to develop on stock exchange analysis or crypto.

Hi @UmutCakar. I think this is a new application proposal. It is better to open a new issue for this.

**Comment by UmutCakar** [comment]
Hi @gormelof ,
Thank you for your feedback.
I'm gonna open it up as soon as a new issue.

**Comment by ozziest** [comment]
Hi @gormelof,

Yes i was thinking an application like you have described.

**Comment by ozziest** [comment]
We have talked about this topic online and we decided it is not a good project for us now.
