### ISSUE TITLE
Online tutorial search application

### ISSUE THREAD

**Issue by gormelof** [aftershift/aftershift.github.io#3]
Think of a user who wants to study online.
Udemy, Pluralsight etc. goes to such practices, it searches to find the proper tutorial.

We can develop an application in which the user can search for tutorial in one platform.
For this we can benefit from the APIs of the online tutorial sites.

**Comment by ozziest** [comment]
I liked the idea. :)

**Comment by ismaildenzzz** [comment]
Hi everyone,

I liked this idea but maybe a scenario with personal training coach and training goals can be more pleasant.

**Comment by ozziest** [comment]
@ismaildenzzz actually I was thinking about a scenario like you mentioned. For example when I was a team lead in my former company, I used to give tasks to internship students. It was very helpful for them. I was providing some keywords and they was researching about it, after the researching period I want to see something as the final task. If the interns can do the final task, it was meaning that they have learnt what i want. 

Maybe we can create a social learning platform which has got mentors and students. Mentors can describe some tasks and if a student claim that he/she perform the task, mentor decide it he/she passed or fail. 

But this is completely different application which @gormelof's suggestion.

**Comment by gormelof** [comment]
@ozziest yes this is a completely different application that you have suggested but I liked it.

**Comment by ozziest** [comment]
We have talked about this topic and we decided to convert the project a little bit. We are going to create an application which can be described as education portal between intern and mentors.

**Comment by ozziest** [comment]
https://github.com/aftershift/backend
https://github.com/aftershift/front-end
