### ISSUE TITLE
Mockup Drawer

### ISSUE THREAD

**Issue by ozziest** [aftershift/aftershift.github.io#5]
I've searched some sketch application to draw some application sketch. But the problem is they are too complicated to use. Maybe we can create a basic sketch drawing tools which can work on browser with JavaScript. We can support Bootstrap grid system and people can drag & drop some basic components such as textbox, selectbox, textarea and etc. It doesn't mean we should show a real textbox. We can prepare some basic components. User can import and exports the sketch. Sketch's format can be JSON.

**Comment by ismaildenzzz** [comment]
I do not know. I did not like this topic too much. Because i don’t think that such an application is much needed.

But i wonder about the ideas of our other friends.

**Comment by ozziest** [comment]
We have talked about this topic online and we decided it is not a good project for us now.
