### ISSUE TITLE
Mobile application that prevents quota overrun

### ISSUE THREAD

**Issue by UmutCakar** [aftershift/aftershift.github.io#6]
The situation we encountered in many operators.

They take money from you to prevent the quota being exceeded.
Internet, minutes, etc. We can monitor, search, or block internet connection.

**Comment by ozziest** [comment]
Actually there are a lot of apps in market. Even my cell phone has got some application to control quota. I don't think that this is a good idea.

**Comment by UmutCakar** [comment]
Yes, but because it is paid we can do the free.

**Comment by ozziest** [comment]
We have talked about this topic online and we decided it is not a good project for us now.
